# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-Apache2
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for Eden (Llama 3.1) model golden values and checkpoint conversion.

Ported from sub-packages/bionemo-evo2/tests/bionemo/evo2/models/test_llama.py.
These tests verify that the NeMo2→mbridge converted Eden 7B checkpoint produces
outputs matching stored golden reference values.
"""

import copy
import glob
import os
import shlex
import subprocess
from pathlib import Path

import pytest
import torch
from transformers import AutoModelForCausalLM

from bionemo.core.data.load import load
from bionemo.evo2.run.predict import batch_collator

from .utils import find_free_network_port, is_a6000_gpu


PRETEST_ENV = copy.deepcopy(os.environ)

PBSS_SKIP = pytest.mark.skipif(
    os.environ.get("BIONEMO_DATA_SOURCE") != "pbss",
    reason="Test data is not available on NGC — run with BIONEMO_DATA_SOURCE=pbss",
)
CI_SKIP = pytest.mark.skipif(bool(os.environ.get("CI")), reason="Skip in CI due to disk space / memory")


@pytest.fixture(scope="module")
def eden_golden_data():
    """Golden reference data for Eden Llama inference."""
    return load("evo2_llama/eden_llama_og2_step_182313_on_evo2_rrna_highly_conserved_PMC4140814:1.0")


@pytest.fixture(scope="module")
def eden_7b_ckpt_path(mbridge_checkpoint_eden_7b) -> Path:
    """Module-scoped alias for the session-scoped Eden 7B mbridge checkpoint."""
    return mbridge_checkpoint_eden_7b


@PBSS_SKIP
@CI_SKIP
@pytest.mark.slow
def test_golden_values_llama(tmp_path, eden_golden_data, eden_7b_ckpt_path):
    """Verify that Eden 7B mbridge checkpoint produces outputs matching stored golden values.

    Runs predict_evo2 on a FASTA file and compares token_logits against reference outputs
    generated by the original NeMo2 model. Tolerance is atol=0.5 (matching the original test).
    """
    fasta_path = eden_golden_data / "ribosomal_rrna_highly_conserved_PMC4140814.fasta"
    gold_values_path = eden_golden_data / "predictions__rank_0__dp_rank_0.pt"

    output_dir = tmp_path / "predictions_llama"

    env = copy.deepcopy(PRETEST_ENV)
    if is_a6000_gpu():
        env["NCCL_P2P_DISABLE"] = "1"

    open_port = find_free_network_port()
    command = (
        f"torchrun --nproc_per_node 1 --nnodes 1 --master_port {open_port} "
        f"-m bionemo.evo2.run.predict "
        f"--fasta {fasta_path} --ckpt-dir {eden_7b_ckpt_path} "
        f"--output-dir {output_dir} "
        f"--eden-tokenizer "
        f"--micro-batch-size 1 --write-interval epoch "
        f"--num-nodes 1 --devices 1"
    )

    result = subprocess.run(shlex.split(command), check=False, cwd=tmp_path, capture_output=True, env=env, text=True)
    if result.returncode != 0:
        print(f"STDOUT:\n{result.stdout}")
        print(f"STDERR:\n{result.stderr}")
    assert result.returncode == 0, f"predict_evo2 failed with code {result.returncode}"

    pred_files = sorted(glob.glob(str(output_dir / "predictions__rank_*__dp_rank_*.pt")))
    assert len(pred_files) >= 1, f"Expected at least 1 prediction file, got {len(pred_files)}"

    preds = [torch.load(pf, weights_only=True) for pf in pred_files]
    predictions = batch_collator(
        [p for p in preds if p is not None],
        batch_dim=0,
        seq_dim=1,
        batch_dim_key_defaults={},
        seq_dim_key_defaults={},
    )
    gold_values = torch.load(gold_values_path, weights_only=True)

    assert predictions["token_logits"].shape == gold_values["token_logits"].shape, (
        f"Shape mismatch: {predictions['token_logits'].shape} vs {gold_values['token_logits'].shape}"
    )
    torch.testing.assert_close(predictions["token_logits"], gold_values["token_logits"], atol=0.5, rtol=0)


@PBSS_SKIP
@CI_SKIP
@pytest.mark.slow
def test_checkpoint_conversion_llama(tmp_path, eden_golden_data, eden_7b_ckpt_path):
    """Verify that NeMo2→mbridge→HF conversion produces a valid HuggingFace model.

    Exports the mbridge checkpoint to HuggingFace format, loads it with AutoModelForCausalLM,
    runs a forward pass on the golden reference sequence, and compares logits against golden values.
    """
    fasta_path = eden_golden_data / "ribosomal_rrna_highly_conserved_PMC4140814.fasta"
    gold_values_path = eden_golden_data / "predictions__rank_0__dp_rank_0.pt"

    roundtrip_helper = Path(__file__).parent / "_eden_roundtrip_helper.py"

    hf_dir = tmp_path / "hf_checkpoint"
    env = copy.deepcopy(PRETEST_ENV)
    if is_a6000_gpu():
        env["NCCL_P2P_DISABLE"] = "1"

    open_port = find_free_network_port()
    cmd = (
        f"torchrun --nproc_per_node 1 --nnodes 1 --master_port {open_port} "
        f"{roundtrip_helper} --mode export "
        f"--ckpt-dir {eden_7b_ckpt_path} --hf-output-dir {hf_dir}"
    )
    result = subprocess.run(shlex.split(cmd), check=False, capture_output=True, text=True, env=env)
    if result.returncode != 0:
        print(f"EXPORT STDOUT:\n{result.stdout}")
        print(f"EXPORT STDERR:\n{result.stderr}")
    assert result.returncode == 0, f"mbridge→HF export failed: {result.stderr[-2000:]}"
    assert hf_dir.exists(), f"HF export dir not created at {hf_dir}"

    hf_model = AutoModelForCausalLM.from_pretrained(
        hf_dir,
        torch_dtype=torch.bfloat16,
        local_files_only=True,
        use_cache=False,
    ).eval()

    with open(fasta_path) as f:
        fasta_seq = f.readlines()[1].strip()
    input_ids = torch.tensor([ord(c) for c in fasta_seq]).unsqueeze(0)

    with torch.no_grad():
        outputs = hf_model(input_ids)

    gold_values = torch.load(gold_values_path, weights_only=True)
    assert outputs.logits.shape == gold_values["token_logits"].shape, (
        f"Shape mismatch: {outputs.logits.shape} vs {gold_values['token_logits'].shape}"
    )
    torch.testing.assert_close(outputs.logits, gold_values["token_logits"].to(dtype=torch.bfloat16), atol=0.5, rtol=0)
