name: "BioNemo Image Build and Unit Tests"

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"
      - "dependabot/**"
  merge_group:
    types: [checks_requested]
  schedule:
    - cron: "0 7 * * *" # Runs at 7 AM UTC daily (12 AM MST)

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements-dev.txt
      - run: ./ci/scripts/static_checks.sh

  build-bionemo-image:
    needs: pre-commit
    runs-on: linux-amd64-cpu4
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'SKIP_CI') }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=${{ github.run_id }}

      # This action sets up our cache-from and cache-to flags appropriately; see the README of this action for more
      # info. It doesn't seem to cache correctly for merge_group events, so we need to add that as an extra argument in
      # the step below. There's probably a slight optimization to be had here by caching from the pr- caches for
      # merge_group events. See https://github.com/int128/docker-build-cache-config-action/issues/1005 for more info.
      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/build-cache
          extra-cache-from: "type=registry,ref=ghcr.io/${{ github.repository }}/build-cache:main"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

  run-tests:
    needs: build-bionemo-image
    runs-on: linux-amd64-gpu-l4-latest-1
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        # Tests in this stage generate code coverage metrics for the repository
        # Coverage data is uploaded to Codecov in subsequent stages
        env:
          BIONEMO_DATA_SOURCE: ngc
        run: ./ci/scripts/run_pytest.sh --no-nbval --skip-slow

      - name: Run slow tests
        if: |
          github.event_name == 'merge_group' || github.event_name == 'schedule' ||
          (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'INCLUDE_SLOW_TESTS'))
        env:
          BIONEMO_DATA_SOURCE: ngc
        # Not every sub-package has slow tests, and since some sub-packages have tests under the same name we need
        #  to run package by package like we do with the fast tests.
        run: ./ci/scripts/run_pytest.sh --no-nbval --only-slow --allow-no-tests

      - name: Run notebook tests
        if: |
          github.event_name == 'merge_group' || github.event_name == 'schedule' ||
          (github.event_name == 'pull_request' &&
            contains(github.event.pull_request.labels.*.name, 'INCLUDE_NOTEBOOKS_TESTS'))
        env:
          BIONEMO_DATA_SOURCE: ngc
        run: pytest -v --nbval-lax -p no:python docs/ sub-packages/

      - name: Upload coverage to Codecov
        # Don't run coverage on merge queue or nightly CI to avoid duplicating reports
        # to codecov. See https://github.com/matplotlib/napari-matplotlib/issues/155
        if: github.event_name != 'merge_group' && github.event_name != 'schedule'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        # Don't run coverage on merge queue or nightly CI to avoid duplicating reports
        # to codecov. See https://github.com/matplotlib/napari-matplotlib/issues/155
        if: ${{ !cancelled() && github.event_name != 'merge_group' && github.event_name != 'schedule' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
